<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.10.2" name="small-tileset" tilewidth="16" tileheight="16" tilecount="80" columns="10">
 <image source="small-tileset.png" width="160" height="128"/>
 <tile id="0" type="sand_stone_NW"/>
 <tile id="1" type="sand_shadow_N"/>
 <tile id="2" type="sand_stone_NE"/>
 <tile id="3" type="wall_NW"/>
 <tile id="4" type="wall_S"/>
 <tile id="5" type="wall_S"/>
 <tile id="6" type="wall_S"/>
 <tile id="7" type="wall_S"/>
 <tile id="8" type="wall_S"/>
 <tile id="9" type="wall_NE"/>
 <tile id="10" type="sand_shadow_W"/>
 <tile id="11" type="empty"/>
 <tile id="12" type="sand_shadow_E"/>
 <tile id="15" type="wall_N"/>
 <tile id="16" type="wall_N"/>
 <tile id="17" type="wall_N"/>
 <tile id="20" type="sand_stone_SW"/>
 <tile id="21" type="sand_shadow_S"/>
 <tile id="22" type="sand_stone_SE"/>
 <tile id="25" type="wall_2"/>
 <tile id="26" type="wall"/>
 <tile id="27" type="wall_2"/>
 <tile id="30" type="empty"/>
 <tile id="31" type="sand_1_NW"/>
 <tile id="32" type="sand_1_NE"/>
 <tile id="40" type="empty"/>
 <tile id="41" type="sand_1_SW"/>
 <tile id="42" type="sand_1_SE"/>
 <tile id="50" type="sand_shadow_NW"/>
 <tile id="51" type="sand_shadow_1_N"/>
 <tile id="52" type="sand_shadow_NE"/>
 <tile id="55" type="wall_S"/>
 <tile id="56" type="wall_S"/>
 <tile id="57" type="wall_S"/>
 <tile id="60" type="sand_shadow_1_W"/>
 <tile id="61" type="empty"/>
 <tile id="62" type="sand_shadow_1_E"/>
 <tile id="70" type="sand_shadow_SW"/>
 <tile id="71" type="sand_shadow_1_S"/>
 <tile id="72" type="sand_shadow_SE"/>
 <tile id="74" type="wall_window"/>
 <tile id="75" type="wall_2"/>
 <tile id="77" type="wall"/>
 <tile id="78" type="wall_2"/>
</tileset>
